# Generated by Django 2.0.7 on 2019-07-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
                ('procesador', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
            ],
        ),
    ]
