# Generated by Django 2.0.7 on 2019-07-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_camara_minicomponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camaras', models.ManyToManyField(to='tienda.camara')),
                ('latops', models.ManyToManyField(to='tienda.laptop')),
                ('minicomponentes', models.ManyToManyField(to='tienda.minicomponente')),
            ],
        ),
    ]
